/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SitemapImagesDotxmlRouteImport } from './routes/sitemap-images[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsSitemapDotxmlRouteImport } from './routes/news-sitemap[.]xml'
import { Route as NamesRouteImport } from './routes/names'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CostPlannerRouteImport } from './routes/cost-planner'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CareRouteImport } from './routes/care'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodsIndexRouteImport } from './routes/foods.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as BreedsIndexRouteImport } from './routes/breeds.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as TagIdRouteImport } from './routes/tag.$id'
import { Route as FoodsSlugRouteImport } from './routes/foods.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BreedsSlugRouteImport } from './routes/breeds.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiGenerateNamesRouteImport } from './routes/api/generate-names'
import { Route as ApiAnalyzeImageRouteImport } from './routes/api/analyze-image'
import { Route as ApiAiTranslateRouteImport } from './routes/api/ai-translate'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin-users'
import { Route as AiSlugRouteImport } from './routes/ai.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTranslationsRouteImport } from './routes/admin.translations'
import { Route as AdminToolsRouteImport } from './routes/admin.tools'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminFoodsRouteImport } from './routes/admin.foods'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBreedsRouteImport } from './routes/admin.breeds'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAffiliatesRouteImport } from './routes/admin.affiliates'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as EmbedToolsSlugRouteImport } from './routes/embed.tools.$slug'
import { Route as DashboardPetsIdRouteImport } from './routes/dashboard.pets.$id'
import { Route as ApiAuthGoogleVerifyRouteImport } from './routes/api/auth/google-verify'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapImagesDotxmlRoute = SitemapImagesDotxmlRouteImport.update({
  id: '/sitemap-images.xml',
  path: '/sitemap-images.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSitemapDotxmlRoute = NewsSitemapDotxmlRouteImport.update({
  id: '/news-sitemap.xml',
  path: '/news-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NamesRoute = NamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CostPlannerRoute = CostPlannerRouteImport.update({
  id: '/cost-planner',
  path: '/cost-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsIndexRoute = FoodsIndexRouteImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedsIndexRoute = BreedsIndexRouteImport.update({
  id: '/breeds/',
  path: '/breeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagIdRoute = TagIdRouteImport.update({
  id: '/tag/$id',
  path: '/tag/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsSlugRoute = FoodsSlugRouteImport.update({
  id: '/foods/$slug',
  path: '/foods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedsSlugRoute = BreedsSlugRouteImport.update({
  id: '/breeds/$slug',
  path: '/breeds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateNamesRoute = ApiGenerateNamesRouteImport.update({
  id: '/api/generate-names',
  path: '/api/generate-names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeImageRoute = ApiAnalyzeImageRouteImport.update({
  id: '/api/analyze-image',
  path: '/api/analyze-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTranslateRoute = ApiAiTranslateRouteImport.update({
  id: '/api/ai-translate',
  path: '/api/ai-translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin-users',
  path: '/api/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSlugRoute = AiSlugRouteImport.update({
  id: '/ai/$slug',
  path: '/ai/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFoodsRoute = AdminFoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBreedsRoute = AdminBreedsRouteImport.update({
  id: '/breeds',
  path: '/breeds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const EmbedToolsSlugRoute = EmbedToolsSlugRouteImport.update({
  id: '/embed/tools/$slug',
  path: '/embed/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPetsIdRoute = DashboardPetsIdRouteImport.update({
  id: '/dashboard/pets/$id',
  path: '/dashboard/pets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleVerifyRoute = ApiAuthGoogleVerifyRouteImport.update({
  id: '/api/auth/google-verify',
  path: '/api/auth/google-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/care': typeof CareRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cost-planner': typeof CostPlannerRoute
  '/disclaimer': typeof DisclaimerRoute
  '/names': typeof NamesRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/breeds': typeof AdminBreedsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai/$slug': typeof AiSlugRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-translate': typeof ApiAiTranslateRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/generate-names': typeof ApiGenerateNamesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/breeds/$slug': typeof BreedsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/tag/$id': typeof TagIdRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ai/': typeof AiIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/breeds/': typeof BreedsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/foods/': typeof FoodsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/api/auth/google-verify': typeof ApiAuthGoogleVerifyRoute
  '/dashboard/pets/$id': typeof DashboardPetsIdRoute
  '/embed/tools/$slug': typeof EmbedToolsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/care': typeof CareRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cost-planner': typeof CostPlannerRoute
  '/disclaimer': typeof DisclaimerRoute
  '/names': typeof NamesRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/breeds': typeof AdminBreedsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai/$slug': typeof AiSlugRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-translate': typeof ApiAiTranslateRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/generate-names': typeof ApiGenerateNamesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/breeds/$slug': typeof BreedsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/tag/$id': typeof TagIdRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/ai': typeof AiIndexRoute
  '/blog': typeof BlogIndexRoute
  '/breeds': typeof BreedsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/foods': typeof FoodsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/api/auth/google-verify': typeof ApiAuthGoogleVerifyRoute
  '/dashboard/pets/$id': typeof DashboardPetsIdRoute
  '/embed/tools/$slug': typeof EmbedToolsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/care': typeof CareRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cost-planner': typeof CostPlannerRoute
  '/disclaimer': typeof DisclaimerRoute
  '/names': typeof NamesRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/breeds': typeof AdminBreedsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/foods': typeof AdminFoodsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai/$slug': typeof AiSlugRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/ai-translate': typeof ApiAiTranslateRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/generate-names': typeof ApiGenerateNamesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/breeds/$slug': typeof BreedsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/tag/$id': typeof TagIdRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ai/': typeof AiIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/breeds/': typeof BreedsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/foods/': typeof FoodsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/api/auth/google-verify': typeof ApiAuthGoogleVerifyRoute
  '/dashboard/pets/$id': typeof DashboardPetsIdRoute
  '/embed/tools/$slug': typeof EmbedToolsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/care'
    | '/compare'
    | '/contact'
    | '/cost-planner'
    | '/disclaimer'
    | '/names'
    | '/news-sitemap.xml'
    | '/privacy'
    | '/rss.xml'
    | '/search'
    | '/sitemap-images.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/ads'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/breeds'
    | '/admin/categories'
    | '/admin/email-templates'
    | '/admin/faqs'
    | '/admin/foods'
    | '/admin/links'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/tools'
    | '/admin/translations'
    | '/admin/users'
    | '/ai/$slug'
    | '/api/admin-users'
    | '/api/ai-chat'
    | '/api/ai-translate'
    | '/api/analyze-image'
    | '/api/generate-names'
    | '/blog/$slug'
    | '/breeds/$slug'
    | '/categories/$slug'
    | '/foods/$slug'
    | '/tag/$id'
    | '/tools/$slug'
    | '/admin/'
    | '/ai/'
    | '/blog/'
    | '/breeds/'
    | '/categories/'
    | '/dashboard/'
    | '/foods/'
    | '/admin/posts/$id'
    | '/api/auth/google-verify'
    | '/dashboard/pets/$id'
    | '/embed/tools/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/care'
    | '/compare'
    | '/contact'
    | '/cost-planner'
    | '/disclaimer'
    | '/names'
    | '/news-sitemap.xml'
    | '/privacy'
    | '/rss.xml'
    | '/search'
    | '/sitemap-images.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/ads'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/breeds'
    | '/admin/categories'
    | '/admin/email-templates'
    | '/admin/faqs'
    | '/admin/foods'
    | '/admin/links'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/tools'
    | '/admin/translations'
    | '/admin/users'
    | '/ai/$slug'
    | '/api/admin-users'
    | '/api/ai-chat'
    | '/api/ai-translate'
    | '/api/analyze-image'
    | '/api/generate-names'
    | '/blog/$slug'
    | '/breeds/$slug'
    | '/categories/$slug'
    | '/foods/$slug'
    | '/tag/$id'
    | '/tools/$slug'
    | '/admin'
    | '/ai'
    | '/blog'
    | '/breeds'
    | '/categories'
    | '/dashboard'
    | '/foods'
    | '/admin/posts/$id'
    | '/api/auth/google-verify'
    | '/dashboard/pets/$id'
    | '/embed/tools/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/care'
    | '/compare'
    | '/contact'
    | '/cost-planner'
    | '/disclaimer'
    | '/names'
    | '/news-sitemap.xml'
    | '/privacy'
    | '/rss.xml'
    | '/search'
    | '/sitemap-images.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/ads'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/breeds'
    | '/admin/categories'
    | '/admin/email-templates'
    | '/admin/faqs'
    | '/admin/foods'
    | '/admin/links'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/tools'
    | '/admin/translations'
    | '/admin/users'
    | '/ai/$slug'
    | '/api/admin-users'
    | '/api/ai-chat'
    | '/api/ai-translate'
    | '/api/analyze-image'
    | '/api/generate-names'
    | '/blog/$slug'
    | '/breeds/$slug'
    | '/categories/$slug'
    | '/foods/$slug'
    | '/tag/$id'
    | '/tools/$slug'
    | '/admin/'
    | '/ai/'
    | '/blog/'
    | '/breeds/'
    | '/categories/'
    | '/dashboard/'
    | '/foods/'
    | '/admin/posts/$id'
    | '/api/auth/google-verify'
    | '/dashboard/pets/$id'
    | '/embed/tools/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CareRoute: typeof CareRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CostPlannerRoute: typeof CostPlannerRoute
  DisclaimerRoute: typeof DisclaimerRoute
  NamesRoute: typeof NamesRoute
  NewsSitemapDotxmlRoute: typeof NewsSitemapDotxmlRoute
  PrivacyRoute: typeof PrivacyRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SearchRoute: typeof SearchRoute
  SitemapImagesDotxmlRoute: typeof SitemapImagesDotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AiSlugRoute: typeof AiSlugRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiTranslateRoute: typeof ApiAiTranslateRoute
  ApiAnalyzeImageRoute: typeof ApiAnalyzeImageRoute
  ApiGenerateNamesRoute: typeof ApiGenerateNamesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BreedsSlugRoute: typeof BreedsSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  FoodsSlugRoute: typeof FoodsSlugRoute
  TagIdRoute: typeof TagIdRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  AiIndexRoute: typeof AiIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BreedsIndexRoute: typeof BreedsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FoodsIndexRoute: typeof FoodsIndexRoute
  ApiAuthGoogleVerifyRoute: typeof ApiAuthGoogleVerifyRoute
  DashboardPetsIdRoute: typeof DashboardPetsIdRoute
  EmbedToolsSlugRoute: typeof EmbedToolsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-images.xml': {
      id: '/sitemap-images.xml'
      path: '/sitemap-images.xml'
      fullPath: '/sitemap-images.xml'
      preLoaderRoute: typeof SitemapImagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-sitemap.xml': {
      id: '/news-sitemap.xml'
      path: '/news-sitemap.xml'
      fullPath: '/news-sitemap.xml'
      preLoaderRoute: typeof NewsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/names': {
      id: '/names'
      path: '/names'
      fullPath: '/names'
      preLoaderRoute: typeof NamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-planner': {
      id: '/cost-planner'
      path: '/cost-planner'
      fullPath: '/cost-planner'
      preLoaderRoute: typeof CostPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/': {
      id: '/foods/'
      path: '/foods'
      fullPath: '/foods/'
      preLoaderRoute: typeof FoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeds/': {
      id: '/breeds/'
      path: '/breeds'
      fullPath: '/breeds/'
      preLoaderRoute: typeof BreedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$id': {
      id: '/tag/$id'
      path: '/tag/$id'
      fullPath: '/tag/$id'
      preLoaderRoute: typeof TagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/$slug': {
      id: '/foods/$slug'
      path: '/foods/$slug'
      fullPath: '/foods/$slug'
      preLoaderRoute: typeof FoodsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeds/$slug': {
      id: '/breeds/$slug'
      path: '/breeds/$slug'
      fullPath: '/breeds/$slug'
      preLoaderRoute: typeof BreedsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-names': {
      id: '/api/generate-names'
      path: '/api/generate-names'
      fullPath: '/api/generate-names'
      preLoaderRoute: typeof ApiGenerateNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-image': {
      id: '/api/analyze-image'
      path: '/api/analyze-image'
      fullPath: '/api/analyze-image'
      preLoaderRoute: typeof ApiAnalyzeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-translate': {
      id: '/api/ai-translate'
      path: '/api/ai-translate'
      fullPath: '/api/ai-translate'
      preLoaderRoute: typeof ApiAiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-users': {
      id: '/api/admin-users'
      path: '/api/admin-users'
      fullPath: '/api/admin-users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/$slug': {
      id: '/ai/$slug'
      path: '/ai/$slug'
      fullPath: '/ai/$slug'
      preLoaderRoute: typeof AiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/foods': {
      id: '/admin/foods'
      path: '/foods'
      fullPath: '/admin/foods'
      preLoaderRoute: typeof AdminFoodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/breeds': {
      id: '/admin/breeds'
      path: '/breeds'
      fullPath: '/admin/breeds'
      preLoaderRoute: typeof AdminBreedsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/embed/tools/$slug': {
      id: '/embed/tools/$slug'
      path: '/embed/tools/$slug'
      fullPath: '/embed/tools/$slug'
      preLoaderRoute: typeof EmbedToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pets/$id': {
      id: '/dashboard/pets/$id'
      path: '/dashboard/pets/$id'
      fullPath: '/dashboard/pets/$id'
      preLoaderRoute: typeof DashboardPetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google-verify': {
      id: '/api/auth/google-verify'
      path: '/api/auth/google-verify'
      fullPath: '/api/auth/google-verify'
      preLoaderRoute: typeof ApiAuthGoogleVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBreedsRoute: typeof AdminBreedsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminFoodsRoute: typeof AdminFoodsRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminToolsRoute: typeof AdminToolsRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBreedsRoute: AdminBreedsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminFoodsRoute: AdminFoodsRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminToolsRoute: AdminToolsRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CareRoute: CareRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CostPlannerRoute: CostPlannerRoute,
  DisclaimerRoute: DisclaimerRoute,
  NamesRoute: NamesRoute,
  NewsSitemapDotxmlRoute: NewsSitemapDotxmlRoute,
  PrivacyRoute: PrivacyRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SearchRoute: SearchRoute,
  SitemapImagesDotxmlRoute: SitemapImagesDotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AiSlugRoute: AiSlugRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiTranslateRoute: ApiAiTranslateRoute,
  ApiAnalyzeImageRoute: ApiAnalyzeImageRoute,
  ApiGenerateNamesRoute: ApiGenerateNamesRoute,
  BlogSlugRoute: BlogSlugRoute,
  BreedsSlugRoute: BreedsSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  FoodsSlugRoute: FoodsSlugRoute,
  TagIdRoute: TagIdRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  AiIndexRoute: AiIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  BreedsIndexRoute: BreedsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FoodsIndexRoute: FoodsIndexRoute,
  ApiAuthGoogleVerifyRoute: ApiAuthGoogleVerifyRoute,
  DashboardPetsIdRoute: DashboardPetsIdRoute,
  EmbedToolsSlugRoute: EmbedToolsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
